name: '[Package/DS] Pull request'

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'packages/ds/**'

jobs:
  code-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Code Lint
        uses: ./.github/actions/code-lint

  type-checking:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Typecheck
        uses: ./.github/actions/type-checking

  unit-with-coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Unit testing
        uses: ./.github/actions/unit-with-coverage

  build:
    runs-on: ubuntu-latest
    needs: [ code-lint, type-checking, unit-with-coverage ]
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn

      - name: Build Storybook
        run: yarn ds:storybook:build


  netlify-deploy:
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - name: Netlify Actions
        uses: nwtgck/actions-netlify@v1.1.11
        with:
          publish-dir: ${{ github.workspace }}/packages/ds/storybook-static
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1