on:
  workflow_run:
    paths:
      - 'packages/ds/**'
    workflows: ['[Packages/**] Pull request']
    types:
      - completed
      - requested

name: '[Package/DS] Pull request'

jobs:
  build:
    runs-on: ubuntu-latest
    needs: [ code-lint, type-checking, unit-with-coverage ]
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn

      - name: Build Storybook
        run: yarn ds:storybook:build

      - uses: actions/upload-artifact@v2
        with:
          name: storybook
          path: ${{ github.workspace }}/packages/ds/storybook-static


  netlify-deploy:
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Download storybook
        uses: actions/download-artifact@v2
        with:
          name: storybook
          path: ${{ github.workspace }}/packages/ds/storybook-static

      - name: Netlify Actions
        uses: nwtgck/actions-netlify@v1.1.11
        with:
          publish-dir: ${{ github.workspace }}/packages/ds/storybook-static
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1