name: Merge on master

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[SKIP CI]') == false
        uses: actions/checkout@master
        with:
          ref: master
      - name: Use Node.js ${{ matrix.node-version }}
        if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[SKIP CI]') == false
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install environment
        if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[SKIP CI]') == false
        run: yarn install
      - name: Login to github
        if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[SKIP CI]') == false
        env:
          CI: true
          GITHUB_AUTH_TOKEN: ${{ secrets.GSYSTEM_AUTH_TOKEN }}
        run: |
          git checkout master
          git config --global user.name 'thiagokpelo'
          git config --global user.email 'thiagokpelo@gmail.com'
          git remote set-url origin https://x-access-token:${GITHUB_AUTH_TOKEN}@github.com/$GITHUB_REPOSITORY
      - name: Authenticate with Registry
        run: |
          yarn logout
          echo "@gsystem:registry=http://registry.npmjs.org/" > .npmrc
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Deploy
        if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[SKIP CI]') == false
        env:
          CI: true
        run: |
          yarn release -- --force-publish from-package
